# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repo
      - uses: actions/checkout@v3

      # 2. Cache node_modules for faster installs
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Lint your code
      - name: Lint
        run: npm run lint

      # 5. Build the production bundle
      - name: Build
        run: npm run build
