name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repo
      - uses: actions/checkout@v3

      # 2. Cache npm for faster installs
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          # scope the lockfile hash to frontend folder
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 3. Install dependencies in frontend/
      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      # 4. Lint your code in frontend/
      - name: Lint
        working-directory: frontend
        run: npm run lint

      # 5. Build the production bundle in frontend/
      - name: Build
        working-directory: frontend
        run: npm run build
